
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("person/new", "Create person")) ?>
</div>

<?php echo $this->tag->form(array("person/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search person</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="firstname">Firstname</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("firstname", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="lastname">Lastname</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("lastname", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
