
<?php echo $this->tag->form("person/create") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("person", "Go Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<?php echo $this->getContent(); ?>

<div align="center">
    <h1>Create person</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="firstname">Firstname</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("firstname", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="lastname">Lastname</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("lastname", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
